language: csharp
mono: none
dotnet: 3.1
env:
  global:
    - IsTravisCI=true
    - TravisCIConnectionString="server=127.0.0.1;user id=root;password=;database=QuickSQL.Test"
services:
  - mysql
before_install:
 - wget -qO- https://packages.microsoft.com/keys/microsoft.asc
 - sudo add-apt-repository "$(wget -qO- https://packages.microsoft.com/config/ubuntu/16.04/mssql-server-2017.list)"
 - sudo apt-get update
 - sudo apt-get install -y mssql-server
 - sudo /opt/mssql/bin/mssql-conf setup
 - echo 2
 - mysql -u root --password="" < QuickSQL.Tests/travis.sql
install:
 - dotnet restore

script:
 - systemctl status mssql-server --no-pager
 - dotnet tool install --global coveralls.net --version 2.0.0
 - export PATH="$PATH:/home/travis/.dotnet/tools"
 - dotnet test --collect:"XPlat Code Coverage"
 - bash <(curl -s https://codecov.io/bash) -t b15b632a-483f-4088-aa4b-aaf7413481d4
