language: csharp
mono: none
dotnet: 3.1

os: windows
before_script:
 # Use mssqlserver2014-sqllocaldb rather than sqllocaldb package which has an issue:
 # https://dba.stackexchange.com/questions/191393/localdb-v14-creates-wrong-path-for-mdf-files
 - choco install mssqlserver2014-sqllocaldb
 - powershell -Command "Set-ExecutionPolicy Bypass"

env:
  global:
    - IsTravisCI=true
    - TravisCIConnectionString="server=127.0.0.1;user id=root;password=;database=QuickSQL.Test"
services:
  - mysql
before_install:
  - mysql -u root --password="" < QuickSQL.Tests/travis.sql
install:
- dotnet restore

script:
 - powershell -File build.ps1
 - dotnet tool install --global coveralls.net --version 2.0.0
 - export PATH="$PATH:/home/travis/.dotnet/tools"
 - dotnet test --collect:"XPlat Code Coverage"
 - bash <(curl -s https://codecov.io/bash) -t b15b632a-483f-4088-aa4b-aaf7413481d4
