language: csharp
mono: none
dotnet: 3.1
env:
  global:
    - DATABASE_NAME=QuickSQL.Test
    - DATABASE_URL=mysql://root@localhost/$DATABASE_NAME
services:
  - mysql
before_install:
  - mysql -u root --password="" < QuickSQL.Tests/travis.sql
install:
- dotnet restore

script:
 - dotnet tool install --global coveralls.net --version 2.0.0
 - export PATH="$PATH:/home/travis/.dotnet/tools"
 - dotnet test --collect:"XPlat Code Coverage"
 - bash <(curl -s https://codecov.io/bash) -t b15b632a-483f-4088-aa4b-aaf7413481d4
