language: csharp
mono: none
dotnet: 3.1
env:
  global:
    - IsTravisCI=true
    - TravisCIConnectionString="server=127.0.0.1;user id=root;password=;database=QuickSQL.Test"
services:
  - docker
  - mysql
before_install:
  - mysql -u root --password="" < QuickSQL.Tests/travis-mysql.sql
install:
  - dotnet restore
before_script:
  - sudo docker run --name=mssql-server-linux-latest -e 'ACCEPT_EULA=Y' -e 'MSSQL_SA_PASSWORD=YourStrong!Passw0rd' -p 1433:1433 -d microsoft/mssql-server-linux:2017-latest
  - sudo docker cp sqlserver.sql mssql-server-linux-latest:sqlserver.sql
  - sudo docker exec -it mssql-server-linux-latest /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P 'YourStrong!Passw0rd' -i QuickSQL.Tests/travis-mssql.sql
  - sudo docker ps -a
script:
  - dotnet tool install --global coveralls.net --version 2.0.0
  - export PATH="$PATH:/home/travis/.dotnet/tools"
  - dotnet test --collect:"XPlat Code Coverage"
  - bash <(curl -s https://codecov.io/bash) -t b15b632a-483f-4088-aa4b-aaf7413481d4
