language: csharp
mono: none
dotnet: 3.1
env:
  global:
    - IsTravisCI=true
    - TravisCIConnectionString="server=127.0.0.1;user id=root;password=;database=QuickSQL.Test"
services:
  - mysql
before_install:
 - sudo docker pull mcr.microsoft.com/mssql/server:2017-latest
 - mysql -u root --password="" < QuickSQL.Tests/travis.sql
install:
 - dotnet restore

script:
 - dotnet tool install --global coveralls.net --version 2.0.0
 - export PATH="$PATH:/home/travis/.dotnet/tools"
 - dotnet test --collect:"XPlat Code Coverage"
 - bash <(curl -s https://codecov.io/bash) -t b15b632a-483f-4088-aa4b-aaf7413481d4
