# Create Testuser
CREATE USER 'dev'@'localhost' IDENTIFIED BY 'dev';
GRANT SELECT,INSERT,UPDATE,DELETE,CREATE,DROP ON *.* TO 'dev'@'localhost';

CREATE DATABASE IF NOT EXISTS `QuickSQL.Test` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
USE `QuickSQL.Test`;

CREATE TABLE IF NOT EXISTS `LeaderBoard` (
  `Id` int(100) NOT NULL,
  `Rank` varchar(200) DEFAULT NULL,
  `Owner` varchar(200) DEFAULT NULL,
  `Amount` varchar(200) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
ALTER TABLE `LeaderBoard`
  ADD PRIMARY KEY (`Id`);
ALTER TABLE `LeaderBoard`
  MODIFY `Id` int(100) NOT NULL AUTO_INCREMENT;

CREATE TABLE IF NOT EXISTS `SignUp` (
  `Id` int(100) NOT NULL,
  `Address` varchar(200) DEFAULT NULL,
  `PoolId` int(100) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
ALTER TABLE `SignUp`
  ADD PRIMARY KEY (`Id`);
ALTER TABLE `SignUp`
  MODIFY `Id` int(100) NOT NULL AUTO_INCREMENT;
  
CREATE TABLE IF NOT EXISTS `TokenBalances` (
  `Id` int(100) NOT NULL,
  `Token` varchar(200) DEFAULT NULL,
  `Owner` varchar(200) DEFAULT NULL,
  `Amount` varchar(200) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
ALTER TABLE `TokenBalances`
  ADD PRIMARY KEY (`Id`);
ALTER TABLE `TokenBalances`
  MODIFY `Id` int(100) NOT NULL AUTO_INCREMENT;
  
CREATE TABLE IF NOT EXISTS `Wallets` (
  `Id` int(100) NOT NULL,
  `Owner` varchar(200) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
ALTER TABLE `Wallets`
  ADD PRIMARY KEY (`Id`);
ALTER TABLE `Wallets`
  MODIFY `Id` int(100) NOT NULL AUTO_INCREMENT;
  
SHOW TABLES;
